/*
 * This Kotlin source file was generated by the Gradle 'init' task.
 */
package pit.demo


import kotlin.test.Test
import kotlin.test.assertEquals

class AnAmazingPieceOfCodeTest {

    @Test
    fun testAdding() {
        val classUnderTest = AnAmazingPieceOfCode()
        assertEquals(2, classUnderTest.add(1, 1))
    }

    @Test
    fun testDividing() {
        val classUnderTest = AnAmazingPieceOfCode()
        classUnderTest.divide(2, 2)
    }

    @Test
    fun testBiggerOf() {
        val classUnderTest = AnAmazingPieceOfCode()
        assertEquals(3, classUnderTest.biggerOf(2, 3))
        assertEquals(3, classUnderTest.biggerOf(3, 2))
    }


}
