/*
 * This Kotlin source file was generated by the Gradle 'init' task.
 */
package pit.demo

class AnAmazingPieceOfCode {

    fun add(x: Int, y: Int): Int = x + y

    fun divide(x: Int, y: Int): Int = x / y

    fun biggerThan(x: Int, y: Int): Boolean {
        if (x > y) {
            return true
        }
        return false
    }
}
