/*
 * This Kotlin source file was generated by the Gradle 'init' task.
 */
package pit.demo

class AnAmazingPieceOfCode {

    fun add(x: Int, y: Int): Int = x + y

    fun divide(x: Int, y: Int): Int = x / y

    fun biggerOf(x: Int, y: Int): Int {
        if (x > y) {
            return x
        }
        return y
    }
}
