/*
 * This Kotlin source file was generated by the Gradle 'init' task.
 */
package pit.demo

class Library {
    fun someLibraryMethod(): Boolean {
        return true
    }

    fun add(x: Int ,y: Int): Int  =  x + y

    fun divide(x:  Int, y: Int): Int = x / y
}
